name: controle_financeiro
description: Um aplicativo de controle financeiro pessoal
publish_to: 'none' # Remova esta linha se for publicar o pacote no pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.0.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
